/**
 * Olsberg Messaging Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Group for living group or case or whatever
 */
export interface Group { 
    /**
     * Group ID
     */
    groupId?: string;
    /**
     * Name of the group
     */
    groupName?: string;
    /**
     * List of all users in this group
     */
    users?: Array<object>;
    /**
     * List of all group chats related to this group
     */
    groupChats?: Array<object>;
}

